name: app_bangiay_doan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.18.0
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.1.0
  sqflite: ^2.3.3+1
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/images/
    - assets/images/products/
    - assets/images/Logo1.png
